on: [push]

jobs:
  build_deb_job:
    runs-on: ubuntu-latest
    name: A job to build deb packages
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build arm32v7
        uses: docker/build-push-action@v4
        with:
          push: false
          context: .
          load: true
          tags: cross-compile:latest-arm32v7
          file: ./Dockerfile-arm32v7
      - name: mkdir build-arm32v7
        run: mkdir build-arm32v7
      - name: run arm32v7
        run: docker run --rm -v $PWD/build-arm32v7:/build -v $PWD:/src cross-compile:latest-arm32v7
      - name: artifact .deb file from build-arm32v7
        uses: actions/upload-artifact@v2
        with:
          name: build-arm32v7
          path: build-arm32v7/*.deb
