on: [push]

jobs:
  build_deb_job:
    runs-on: ubuntu-latest
    name: A job to build deb packages
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: build arm32v7
        uses: ./action.yml
      - name: build amd64
        uses: ./action-amd64.yml