on: [push]

jobs:
  build_deb_job:
    runs-on: ubuntu-latest
    name: A job to build deb packages
    steps:
      - name: build arm32v7
        uses: ./.github/actions/action-arm32v7.yml
      - name: build amd64
        uses: ./.github/actions/action-amd64.yml